spring.mongodb.uri=mongodb+srv://tylerth852_db_user:748223@ecommerce.pwwkptv.mongodb.net/ecommerce?appName=ecommerce
# Keep this for UUID support
spring.data.mongodb.uuid-representation=standard

spring.main.allow-circular-references=true
spring.data.mongodb.auto-index-creation=true
server.port=${PORT:8080}

application.security.jwt.secret-key=HrvV4DTGNVnJxHVjMtWxSRCVPH0j9dcIoRuwuhvK6cH

paystack.secret.key=sk_test_eacfd0e2cd4f4327b9c7adc190f9fdc89e5748bc
paystack.base.url=https://api.paystack.co

spring.mail.username=muhammedsulai4@gmail.com
spring.mail.password=plvtgmerwosrtuak
spring.mail.port=587
spring.mail.host=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.enabled=true



